### ISSUE TITLE
How to pre-train and evaluate on all three viewpoints?

### ISSUE THREAD

**Issue by liuyuex97** [Levigty/AimCLR#1]

**Comment by liuyuex97** [comment]
Nevermind, I found the ensemble file : )

**Comment by Levigty** [comment]
Thank you for your attention to our work. If your GPU's memory is enough, you can also train the model of three streams in one time, just like the script:[https://github.com/LinguoLi/CrosSCLR/blob/main/net/crossclr_3views.py](https://github.com/LinguoLi/CrosSCLR/blob/main/net/crossclr_3views.py).
