### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/data/gty'

### ISSUE THREAD

**Issue by wys2929** [Levigty/AimCLR#10]
when i run:
$ python main.py linear_evaluation --config config/ntu60/linear_eval/linear_eval_aimclr_xview_joint.yaml
out:
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    p = Processor(sys.argv[2:])
  File "/home/xxx/project1/AimCLR/processor/processor.py", line 43, in __init__
    self.init_environment()
  File "/home/xxx/project1/AimCLR/processor/processor.py", line 76, in init_environment
    super().init_environment()
  File "/home/xxx/project1/AimCLR/processor/io.py", line 55, in init_environment
    self.io.save_arg(self.arg)
  File "/home/xxx/anaconda3/envs/TEST2/lib/python3.7/site-packages/torchlight-1.0-py3.7.egg/torchlight/io.py", line 116, in save_arg
  File "/home/xxx/anaconda3/envs/TEST2/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/xxx/anaconda3/envs/TEST2/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/xxx/anaconda3/envs/TEST2/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/xxx/anaconda3/envs/TEST2/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data/gty'

my .yaml:
work_dir: /data/gty/AAAI_github/ntu60_cv/aimclr_joint/linear_eval

weights: /data/gty/released_model/ntu60_xview_joint.pt
# weights: /data/gty/AAAI_github/ntu60_cv/aimclr_joint/pretext/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /home/wuyushan/project1/data/NTU60_frame50/xview/train_position.npy
  label_path: /home/wuyushan/project1/data/NTU60_frame50/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /home/xxx/project1/data/NTU60_frame50/xview/val_position.npy
  label_path: /home/xxx/project1/data/NTU60_frame50/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [1]  # 3
batch_size: 64  # 128
test_batch_size: 64  # 128
num_epoch: 100
stream: 'joint'

# log
save_interval: -1
eval_interval: 5

i don't know why,can you help me,please!

**Comment by wys2929** [comment]
my .yaml:
work_dir: /data/gty/AAAI_github/ntu60_cv/aimclr_joint/linear_eval

weights: /data/gty/released_model/ntu60_xview_joint.pt

ignore_weights: [encoder_q.fc, encoder_k, queue]

train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /home/xxx/project1/data/NTU60_frame50/xview/train_position.npy
  label_path: /home/xxx/project1/data/NTU60_frame50/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /home/xxx/project1/data/NTU60_frame50/xview/val_position.npy
  label_path: /home/xxx/project1/data/NTU60_frame50/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False

  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

device: [1]
batch_size: 64  
test_batch_size: 64  
num_epoch: 100
stream: 'joint'

save_interval: -1
eval_interval: 5

**Comment by Levigty** [comment]
Sorry for the late reply. You should change the data path to a valid address accessible on your server.
