### ISSUE TITLE
How to calculate the comprehensive results of the three streams

### ISSUE THREAD

**Issue by wys2929** [Levigty/AimCLR#11]
Hello, for the papers,“For all the reported results of three streams, we use the weights of [0.6, 0.6, 0.4] for weighted fusion like other multi-stream GCN methods.”
But I still don’t understand, can you teach me how to calculate the comprehensive results of the three streams?
For example, how did the 83.8 in the last line of the fourth column in Table II calculated?
![image](https://user-images.githubusercontent.com/102473594/203781743-360b02b8-e46b-49ff-939f-ed84e5aa590b.png)

**Comment by Levigty** [comment]
Just simply ensemble the results. See 'ensemble_ntu_cs.py'. Recently we are exploring more efficient aggregation methods.

**Comment by wys2929** [comment]
Thank you for your prompt reply！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Levigty/AimCLR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 晚上8:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Levigty/AimCLR] How to calculate the comprehensive results of the three streams (Issue #11)





 
Just simply ensemble the results. See 'ensemble_ntu_cs.py'. Recently we are exploring more efficient aggregation methods.
