### ISSUE TITLE
Request for sharing dataset

### ISSUE THREAD

**Issue by zhy0860** [Levigty/AimCLR#2]
Thanks for your time, I encounter some problems using Google Drive to download PKUMMD dataset. It can help a lot if  both parts of the datasets can be shared on BaiduYun if it is convenient for you, I appreciate it a lot for your kindness.

By the way, is the preprocessing and experiment settings same for part1 and part2? Looking forward to your reply.

**Comment by Levigty** [comment]
Thank you for your attention to our work. Considering the transfer rate, I'm sorry that I only gave a link to Google Drive before. I have uploaded the datasets to BaiduYun today, and the datasets download link is here: [https://pan.baidu.com/s/1NRK1ksRHgng_NkOO1ZYTcQ](https://pan.baidu.com/s/1NRK1ksRHgng_NkOO1ZYTcQ), code: 0211.

For the experimental settings, we did not spend much time exploring the most suitable experimental parameters for each dataset, so the preprocessing and experiment settings are the same. Hope my reply is helpful to you.

**Comment by zhy0860** [comment]
Thanks a lot for the help, could you please upload the raw data or the motion and bone data as well, since the joint along can not do the ensemble experiments. I apologize for the inconvenience, and thanks again for your kindness!

**Comment by Levigty** [comment]
For the raw dataset, I provided the official download link in the readme. The processed joint data is enough, the motion and bone data can be obtained by simple calculation like the code in line 46-75 in processor/pretrain_aimclr.py.

**Comment by zhy0860** [comment]
Appreciate it a lot for your patience.

**Comment by yanghhx** [comment]
Could you please share the NTU120 frame 50 datasets?

**Comment by Levigty** [comment]
In fact, the preprocessing of the NTU-120 dataset is similar to that of the NTU-60 dataset. The file link of the processed NTU-120 is as follows: [NTU-120-frame50](https://drive.google.com/drive/folders/1dn8VMcT9BYi0KHBkVVPFpiGlaTn2GnaX?usp=sharing). Hope it can help you.

**Comment by yanghhx** [comment]
Thanks for your sharing.
















At 2022-03-27 15:39:01, "Gty" ***@***.***> wrote:

In fact, the preprocessing of the NTU-120 dataset is similar to that of the NTU-60 dataset. The file link of the processed NTU-120 is as follows: NTU-120-frame50. Hope it can help you.
