### ISSUE TITLE
What is the difference between KNN and Linear evaluation?

### ISSUE THREAD

**Issue by yanghhx** [Levigty/AimCLR#4]
Your paper has classified as "Notably, the KNN classifier does not require learning extra weights compared with the
linear classifier". What is the "extra weights"？ Can you explain it clearly?

**Comment by Levigty** [comment]
KNN evaluation means that we use the K-Nearest Neighbor (KNN) classifier with a fixed encoder. Linear evaluation means that we fix the encoder and train a classification head (we use FC layer) with SGD optimizer.

**Comment by yanghhx** [comment]
Can I explain it tha the difference between KNN evaluation and Linear evaluation is the different classifier ?










At 2022-03-27 12:56:48, "Gty" ***@***.***> wrote:

KNN evaluation means that we use the K-Nearest Neighbor (KNN) classifier with a fixed encoder. Linear evaluation means that we fix the encoder and train a classification head (we use FC layer) with SGD optimizer.

**Comment by Levigty** [comment]
Yes, different classifier with the fixed encoder.
