### ISSUE TITLE
Preprocessing NTU dataset

### ISSUE THREAD

**Issue by paolomandica** [Levigty/AimCLR#8]
Hi, thank you for sharing your work with the community!
I was intersted in training a model using 150 frames long sequences, but after preprocessing the NTU dataset I ended up with just `.npy` files, while `.pkl` are needed for the label. Could you please share the code to convert the `.npy` files into `.pkl`?
Thank you,
Paolo

**Comment by Levigty** [comment]
For NTU dataset, the  `.pkl` obtained after `tools/ntu_gendata.py` is also suitable for downsample the data to 150 frames with `feeder/preprocess_ntu.py`. No extra code required.
